name: FPP Latest Docker Test

on:
  workflow_dispatch:
  #pull_request:
    #branches: [ "main" ]

jobs:

  docker-test:

    runs-on: ubuntu-latest
    container:
      image: falconchristmas/fpp:latest
      ports:
        - 80
    steps:
    - uses: actions/checkout@v4
      name: Build the Docker image
      
